### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by jinchenyu** [bagh2178/SG-Nav#2]
复现环境：
python3.7
habitat-sim==v0.2.1
habitat-lab==v0.2.1

会遇到缺少参数split_l，不清楚是不是habitat版本问题
"""
Traceback (most recent call last):
  File "SG_Nav.py", line 1366, in <module>
    main()
  File "SG_Nav.py", line 1357, in main
    challenge = habitat.Challenge(eval_remote=False, split_l=args.split_l, split_r=args.split_r)
TypeError: __init__() got an unexpected keyword argument 'split_l'
"""

删除split_l，split_r后会报“TURN_RIGHT_2”的错误
"""
Traceback (most recent call last):
  File "SG_Nav.py", line 1366, in <module>
    main()
  File "SG_Nav.py", line 1358, in main
    challenge = habitat.Challenge(eval_remote=False)
  File "/workspace/llm_nav_v3/habitat-lab/habitat/core/challenge.py", line 16, in __init__
    super().__init__(config_paths, eval_remote=eval_remote)
  File "/workspace/llm_nav_v3/habitat-lab/habitat/core/benchmark.py", line 38, in __init__
    self._env = Env(config=config_env)
  File "/workspace/llm_nav_v3/habitat-lab/habitat/core/env.py", line 116, in __init__
    dataset=self._dataset,
  File "/workspace/llm_nav_v3/habitat-lab/habitat/tasks/registration.py", line 22, in make_task
    return _task(**kwargs)
  File "/workspace/llm_nav_v3/habitat-lab/habitat/tasks/nav/nav.py", line 1262, in __init__
    super().__init__(config=config, sim=sim, dataset=dataset)
  File "/workspace/llm_nav_v3/habitat-lab/habitat/core/embodied_task.py", line 254, in __init__
    entities_config=self._config.ACTIONS,
  File "/workspace/llm_nav_v3/habitat-lab/habitat/core/embodied_task.py", line 266, in _init_entities
    entity_cfg = getattr(entities_config, entity_name)
  File "/home/narwal/anaconda3/envs/sg_nav_v3/lib/python3.7/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: TURN_RIGHT_2
"""

尝试过
habitat-sim==v0.3.1，habitat-lab==v0.3.1
habitat-sim==v0.2.4，habitat-lab==v0.2.4
会出现config yaml格式不兼容的问题https://github.com/bagh2178/SG-Nav/issues/1

habitat-sim==v0.2.4，habitat-lab==v0.2.1
会出现版本不兼容的问题“ModuleNotFoundError: No module named 'habitat_sim.robots'“
应该是habitat-sim v0.2.3，Robots module moved to Habitat-lab，https://github.com/facebookresearch/habitat-sim/releases/tag/v0.2.3

**Comment by bagh2178** [comment]
Thanks for your attention. For habitat-lab, you can install the version provided in our code if you encounter bugs when installing the official version. The installation command is ``pip install -e habitat-lab``.

**Comment by yusirhhh** [comment]
can you slove the problem using  'pip install -e habitat-lab'
